shim-version: v0.3.11@sha256:c38fcc5db743dddf5dc986f67da8732b8a6c473e0e8e54d63826f46da278e290
cvm-version: 0.5.18
cpus: 8
memory: 16384

shim:
  listen-port: 443
  upstream-port: 8089
  paths:
    - /v1/chat/completions
    - /v1/responses
    - /health

containers:
  - name: "websearch-proxy"
    image: ""
    args:
      [
        "-e",
        "EXA_API_KEY=$(awk -F': *' '$1~/^exa_api_key$/{print $2; exit}' /mnt/ramdisk/external-config.yml)",
        "-e",
        "TINFOIL_API_KEY=$(awk -F': *' '$1~/^tinfoil_api_key$/{print $2; exit}' /mnt/ramdisk/external-config.yml)",
        "ghcr.io/tinfoilsh/confidential-websearch:0.0.32",
      ]
