shim-version: v0.3.14@sha256:154c3e15f4d4856fd4b72e83f84da751abd34c76732bb6548bc89d5fa56c24ac
cvm-version: 0.6.7
cpus: 8
memory: 16384

containers:
  - name: "websearch-proxy"
    image: "ghcr.io/tinfoilsh/confidential-websearch:0.1.6"
    secrets:
      - EXA_API_KEY
      - TINFOIL_API_KEY

shim:
  listen-port: 443
  upstream-port: 8089
  paths:
    - /v1/chat/completions
    - /v1/responses
    - /health
