shim-version: v0.3.16@sha256:20220be4487f241e7e2a9af6dd576d20ba35d71307bd777c8dba9ba5da03fb38
cvm-version: 0.6.7
cpus: 8
memory: 16384

containers:
  - name: "websearch-proxy"
    image: "ghcr.io/tinfoilsh/confidential-websearch:0.1.6"
    secrets:
      - EXA_API_KEY
      - TINFOIL_API_KEY

shim:
  listen-port: 443
  upstream-port: 8089
  paths:
    - /v1/chat/completions
    - /v1/responses
    - /health
