shim-version: v0.3.9@sha256:a45eb01f8e5fa3162b804821d53d8e8667a75940a9c1995f29265347efca8009
cvm-version: 0.5.10
cpus: 8
memory: 16384

shim:
  listen-port: 443
  upstream-port: 8089
  publish-attestation: true
  tls-challenge: dns

containers:
  - name: "websearch-proxy"
    image: ""
    args:
      [
        "-e",
        "EXA_API_KEY=$(awk -F': *' '$1~/^exa_api_key$/{print $2; exit}' /mnt/ramdisk/external-config.yml)",
        "ghcr.io/tinfoilsh/confidential-websearch:0.0.10",
      ]
