shim-version: v0.3.2@sha256:2bbbf67720a258f8fb92a470f2368215b97fa5ee92afa117d376e776e34e2373
cvm-version: 0.5.10
cpus: 8
memory: 16384

shim:
  listen-port: 443
  upstream-port: 8089
  publish-attestation: true
  tls-challenge: dns

containers:
  - name: "websearch-proxy"
    image: ""
    args: [
      "-e", "EXA_API_KEY=$(awk -F': *' '$1~/^exa_api_key$/{print $2; exit}' /mnt/ramdisk/external-config.yml)",
      "-e", "BING_API_KEY=$(awk -F': *' '$1~/^bing_api_key$/{print $2; exit}' /mnt/ramdisk/external-config.yml)",
      "ghcr.io/tinfoilsh/confidential-websearch:0.0.5",
    ]
