shim-version: v0.3.12@sha256:b81f2295ae6750d61e94f810ce24077360001b6ec795d13643f3170df29e304d
cvm-version: 0.6.5
cpus: 8
memory: 16384

containers:
  - name: "websearch-proxy"
    image: "ghcr.io/tinfoilsh/confidential-websearch:0.1.2"
    secrets:
      - EXA_API_KEY
      - TINFOIL_API_KEY

shim:
  listen-port: 443
  upstream-port: 8089
  paths:
    - /v1/chat/completions
    - /v1/responses
    - /health
